"""
app/services/email_service.py
Sends emails via Gmail SMTP.
Credentials are passed per-request — user enters them in the dashboard.
No .env setup needed.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_weekly_plan_email(
    sender_email: str,
    sender_app_password: str,
    to_email: str,
    user_name: str,
    business_type: str,
    week_number: int,
    refined_summary: str,
    refined_plan: dict
) -> bool:
    """
    Send the weekly refined plan email.
    sender_email: Gmail address to send FROM (user provides in dashboard)
    sender_app_password: Gmail App Password (user provides in dashboard)
    to_email: address to send TO (can be same or different)
    """

    subject = f"📊 Week {week_number} Strategy Update — {business_type}"

    actions_html = "".join(
        f"<li style='margin-bottom:8px;color:#bbb'>{a}</li>"
        for a in refined_plan.get("actions", [])
    )
    recommendations_html = "".join(
        f"<li style='margin-bottom:8px;color:#bbb'>{r}</li>"
        for r in refined_plan.get("recommendations", [])
    )
    channels_html = ", ".join(refined_plan.get("channels", []))

    html_body = f"""
    <div style="font-family:'Courier New',monospace;background:#0a0a0a;color:#fff;padding:40px;max-width:600px;margin:0 auto;">
        <div style="border-bottom:2px solid #00ff88;padding-bottom:20px;margin-bottom:30px;">
            <p style="color:#00ff88;font-size:11px;letter-spacing:3px;margin:0">AUTONOMOUS BUSINESS OPERATOR AI</p>
            <h1 style="font-size:24px;margin:8px 0 0 0;">Week {week_number} Refined Plan</h1>
            <p style="color:#666;margin:4px 0 0 0;">{business_type} · Hi {user_name} 👋</p>
        </div>

        <div style="background:#111;border:1px solid #222;border-radius:8px;padding:20px;margin-bottom:20px;">
            <h2 style="color:#00ff88;font-size:12px;letter-spacing:1px;margin:0 0 10px;">📋 AI ANALYSIS</h2>
            <p style="color:#aaa;line-height:1.7;margin:0">{refined_summary}</p>
        </div>

        <div style="background:#111;border:1px solid #222;border-radius:8px;padding:20px;margin-bottom:20px;">
            <h2 style="color:#00ff88;font-size:12px;letter-spacing:1px;margin:0 0 10px;">📡 FOCUS CHANNELS</h2>
            <p style="color:#fff;margin:0">{channels_html}</p>
        </div>

        <div style="background:#111;border:1px solid #222;border-radius:8px;padding:20px;margin-bottom:20px;">
            <h2 style="color:#00ff88;font-size:12px;letter-spacing:1px;margin:0 0 10px;">⚡ THIS WEEK'S ACTIONS</h2>
            <ul style="padding-left:20px;margin:0">{actions_html}</ul>
        </div>

        <div style="background:#111;border:1px solid #222;border-radius:8px;padding:20px;margin-bottom:32px;">
            <h2 style="color:#00ff88;font-size:12px;letter-spacing:1px;margin:0 0 10px;">💡 RECOMMENDATIONS</h2>
            <ul style="padding-left:20px;margin:0">{recommendations_html}</ul>
        </div>

        <p style="color:#333;font-size:11px;text-align:center;">
            Generated by Autonomous Business Operator AI · Powered by llama3.2 + RAG Memory
        </p>
    </div>
    """

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = sender_email
        msg["To"] = to_email
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender_email, sender_app_password)
            server.sendmail(sender_email, to_email, msg.as_string())

        print(f"✅ Email sent to {to_email}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("❌ Gmail auth failed — wrong email or app password")
        raise ValueError("Gmail authentication failed. Check your email and App Password.")
    except Exception as e:
        print(f"❌ Email failed: {e}")
        raise ValueError(f"Email send failed: {str(e)}")